version: '3.9'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: coredb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth_service:
    build: ./auth_service
    ports:
      - "8001:8001"
    depends_on:
      - db

  user_service:
    build: ./user_service
    ports:
      - "8002:8002"
    depends_on:
      - db

  stats_service:
    build: ./stats_service
    ports:
      - "8003:8003"
    depends_on:
      - db

volumes:
  postgres_data:
